"""Flags-off parity (feature/wire-research-features): with every research feature flag at its
default (OFF), the API must return exactly what `main` (4c60e3f) returned for the same inputs.

`tests/fixtures/parity_flags_off_main.json` was generated by running `run_parity_scenario()`
below against the UNMODIFIED main code, before any feature-flag code existed on this branch:

    PYTHONPATH=. python tests/test_flags_off_parity.py --write

Do not regenerate it on this branch to make the test pass -- a failure here means a flag-off code
path changed an API output, which is the thing this test exists to catch.

The scenario drives every endpoint main has, through the real FastAPI app and the real fresh
pipeline (services.py), with Pulse and the two ML models mocked the same way tests/test_api.py
does: a measured-EF patient across 30 days that walks through stable, fluid_overload (long enough
for the C3 downgrade), a Pulse crash, a crash-zone completion, cardiac_stress, deconditioning; an
EF-fallback fluid_overload patient; a patient still collecting; plus 404/422 responses.

Normalization is limited to values that legitimately differ between runs: patient UUIDs (mapped to
P1, P2, ... in creation order) and wall-clock timestamps. Floats are compared with
rel_tol=1e-9 so a different numpy/BLAS build can't fail the test on last-bit noise; every string,
key, list length and None is compared exactly.
"""
from __future__ import annotations

import datetime
import json
import math
import pathlib
import re
import sys
import tempfile
from unittest.mock import patch

import pandas as pd

REPO_ROOT = pathlib.Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

GOLDEN_PATH = REPO_ROOT / "tests" / "fixtures" / "parity_flags_off_main.json"

FLAG_ENV_VARS = (
    "PIPELINE_MODE",
    "ENABLE_BCG_MODIFIERS",
    "ENABLE_HR_BASELINE",
    "ENABLE_ALERT_HYSTERESIS",
    "ENABLE_SCENARIO_PERSISTENCE",
)

_TS_RE = re.compile(r"^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}")


def _df(hr_start=71, hr_end=71, map_start=95, map_end=95, co_start=5000, co_end=5000, sv_start=70, sv_end=70):
    return pd.DataFrame(
        {
            "Time(s)": [0, 300, 600],
            "HeartRate(1/min)": [hr_start, (hr_start + hr_end) / 2, hr_end],
            "MeanArterialPressure(mmHg)": [map_start, (map_start + map_end) / 2, map_end],
            "CardiacOutput(mL/min)": [co_start, (co_start + co_end) / 2, co_end],
            "HeartStrokeVolume(mL)": [sv_start, (sv_start + sv_end) / 2, sv_end],
            "OxygenSaturation": [0.97, 0.97, 0.97],
            "LeftHeart-Volume(mL)": [100.0, 120.0, 100.0],
            "LeftHeart-Pressure(mmHg)": [60.0, 10.0, 60.0],
            "ECG-Lead3ElectricPotential(mV)": [0.0, 0.5, 0.0],
        }
    )


NORMAL_DF = _df()
CONGESTED_DF = _df(hr_start=70, hr_end=70, map_start=70, map_end=70)
ACUTE_DF = _df(hr_start=70, hr_end=130, map_start=95, map_end=60, co_start=5000, co_end=3000, sv_start=70, sv_end=40)
FLAT_DF = _df(hr_start=72, hr_end=72, map_start=94, map_end=94)

# day index (0-based reading number) -> (scenario_type, severity, pulse outcome). Days before 20
# never reach the pipeline (window not full).
P1_SCHEDULE = {
    20: ("stable", 0.10, NORMAL_DF),
    21: ("fluid_overload", 0.30, CONGESTED_DF),
    22: ("fluid_overload", 0.30, CONGESTED_DF),
    23: ("fluid_overload", 0.30, CONGESTED_DF),
    24: ("fluid_overload", 0.30, CONGESTED_DF),
    25: ("acute_deterioration", 0.70, "crash"),
    26: ("acute_deterioration", 0.70, ACUTE_DF),
    27: ("cardiac_stress", 0.50, ACUTE_DF),
    28: ("stable", 0.05, NORMAL_DF),
    29: ("deconditioning", 0.20, NORMAL_DF),
}


class _FakeModel:
    def __init__(self, value):
        self.value = value

    def predict(self, x):
        return [self.value] * len(x)


def _reading(i: int) -> dict:
    start = datetime.date(2026, 1, 1)
    return {
        "recorded_date": str(start + datetime.timedelta(days=i)),
        "resting_hr_bpm": 68 + 0.4 * i,
        "spo2_pct": 97 - 0.05 * i,
        "weight_kg": 80 + 0.06 * i,
        "steps_per_day": 6500 - 40 * i,
        "sleep_hours": 7.0 - 0.01 * i,
        "hrv_rmssd_ms": 38 - 0.2 * i,
    }


def _make_client(tmp_dir: pathlib.Path):
    """Same isolation as tests/test_api.py's `client` fixture."""
    from fastapi.testclient import TestClient
    from sqlalchemy import create_engine
    from sqlalchemy.orm import sessionmaker

    from src.api.database import Base, get_db
    from src.api.main import app

    engine = create_engine(f"sqlite:///{tmp_dir / 'parity.db'}", connect_args={"check_same_thread": False})
    TestSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)
    Base.metadata.create_all(bind=engine)

    def override_get_db():
        db = TestSessionLocal()
        try:
            yield db
        finally:
            db.close()

    app.dependency_overrides[get_db] = override_get_db
    patches = [
        patch("src.api.routes.SessionLocal", TestSessionLocal),
        patch("src.api.services.SCENARIOS_DIR", tmp_dir / "scenarios"),
    ]
    return app, TestClient(app), patches, engine


def run_parity_scenario() -> list:
    """Returns a list of (label, status_code, json_body) for every request made, in order."""
    from src.pulse_runner.runner import PulseExecutionError

    out = []

    def record(label, response):
        out.append([label, response.status_code, response.json()])

    with tempfile.TemporaryDirectory(ignore_cleanup_errors=True) as tmp:
        app, client, patches, engine = _make_client(pathlib.Path(tmp))
        for p in patches:
            p.start()
        try:
            with client:
                # --- P1: measured EF, 30 days through the fresh pipeline ---
                r = client.post("/patients", json={"age": 66, "sex": "Male", "height_cm": 175, "weight_kg": 82, "label": "parity P1"})
                record("create P1", r)
                p1 = r.json()["id"]
                record("clinical P1", client.post(f"/patients/{p1}/clinical-report", json={"ejection_fraction_pct": 30, "nt_probnp_pg_ml": 1500}))

                for i in range(30):
                    stype, sev, outcome = P1_SCHEDULE.get(i, ("stable", 0.1, NORMAL_DF))
                    pulse_kwargs = (
                        {"side_effect": PulseExecutionError("simulated crash")}
                        if isinstance(outcome, str) else {"return_value": outcome}
                    )
                    with patch("src.api.services._load_scenario_classifier_models", return_value=(_FakeModel(stype), _FakeModel(sev))), \
                         patch("src.pulse_runner.runner.run_pulse", **pulse_kwargs):
                        record(f"sync P1 day {i}", client.post(f"/patients/{p1}/wearable-sync", json=_reading(i)))
                    if i >= 19:
                        record(f"status P1 day {i}", client.get(f"/patients/{p1}/status"))

                record("history P1", client.get(f"/patients/{p1}/history"))
                record("projection P1", client.get(f"/patients/{p1}/projection"))
                record("report P1", client.get(f"/patients/{p1}/report"))
                record("wearable-history P1", client.get(f"/patients/{p1}/wearable-history"))

                # --- P2: no clinical report -> Tier 1 fallback, fluid_overload with a flat run ---
                r = client.post("/patients", json={"age": 58, "sex": "Female", "height_cm": 162, "weight_kg": 70})
                record("create P2", r)
                p2 = r.json()["id"]
                with patch("src.api.services._load_scenario_classifier_models", return_value=(_FakeModel("fluid_overload"), _FakeModel(0.6))), \
                     patch("src.pulse_runner.runner.run_pulse", return_value=FLAT_DF):
                    for i in range(21):
                        r = client.post(f"/patients/{p2}/wearable-sync", json=_reading(i))
                    record("sync P2 last", r)
                record("status P2", client.get(f"/patients/{p2}/status"))
                record("report P2", client.get(f"/patients/{p2}/report"))

                # --- P3: partial clinical report, still collecting ---
                r = client.post("/patients", json={"age": 45, "sex": "Female", "height_cm": 168, "weight_kg": 64})
                record("create P3", r)
                p3 = r.json()["id"]
                record("clinical P3 EF only", client.post(f"/patients/{p3}/clinical-report", json={"ejection_fraction_pct": 52}))
                for i in range(5):
                    r = client.post(f"/patients/{p3}/wearable-sync", json=_reading(i))
                record("sync P3 day 4", r)
                record("status P3", client.get(f"/patients/{p3}/status"))
                record("projection P3", client.get(f"/patients/{p3}/projection"))
                record("history P3", client.get(f"/patients/{p3}/history"))

                # --- errors and listing ---
                record("status unknown", client.get("/patients/does-not-exist/status"))
                record("create invalid", client.post("/patients", json={"age": -1, "sex": "Male", "height_cm": 175, "weight_kg": 80}))
                record("clinical invalid", client.post(f"/patients/{p1}/clinical-report", json={"ejection_fraction_pct": 150}))
                record("sync invalid", client.post(f"/patients/{p1}/wearable-sync", json={**_reading(40), "spo2_pct": 10}))
                record("list patients", client.get("/patients"))
        finally:
            for p in patches:
                p.stop()
            app.dependency_overrides.clear()
            engine.dispose()
    return _normalize(out)


def _normalize(records: list) -> list:
    ids: dict[str, str] = {}
    for label, _code, body in records:
        if label.startswith("create P") and isinstance(body, dict) and "id" in body:
            ids[body["id"]] = label.split()[-1]

    def walk(x):
        if isinstance(x, dict):
            return {k: walk(v) for k, v in x.items()}
        if isinstance(x, list):
            return [walk(v) for v in x]
        if isinstance(x, str):
            if x in ids:
                return ids[x]
            if _TS_RE.match(x):
                return "<timestamp>"
            for real, alias in ids.items():
                x = x.replace(real, alias)
            return x
        return x

    return walk(records)


def _assert_same(expected, actual, path="$"):
    if isinstance(expected, float) or isinstance(actual, float):
        assert isinstance(actual, (int, float)) and isinstance(expected, (int, float)) and not isinstance(actual, bool), \
            f"{path}: type differs ({expected!r} vs {actual!r})"
        assert math.isclose(expected, actual, rel_tol=1e-9, abs_tol=1e-12), f"{path}: {expected!r} != {actual!r}"
        return
    assert type(expected) is type(actual), f"{path}: type differs ({type(expected).__name__} vs {type(actual).__name__})"
    if isinstance(expected, dict):
        assert expected.keys() == actual.keys(), (
            f"{path}: keys differ; only on main={sorted(expected.keys() - actual.keys())}, "
            f"only on branch={sorted(actual.keys() - expected.keys())}"
        )
        for k in expected:
            _assert_same(expected[k], actual[k], f"{path}.{k}")
    elif isinstance(expected, list):
        assert len(expected) == len(actual), f"{path}: length {len(expected)} != {len(actual)}"
        for i, (e, a) in enumerate(zip(expected, actual)):
            _assert_same(e, a, f"{path}[{i}]")
    else:
        assert expected == actual, f"{path}: {expected!r} != {actual!r}"


def test_api_outputs_identical_to_main_with_all_flags_unset(monkeypatch):
    for var in FLAG_ENV_VARS:
        monkeypatch.delenv(var, raising=False)
    expected = json.loads(GOLDEN_PATH.read_text())
    _assert_same(expected, run_parity_scenario())


def test_api_outputs_identical_to_main_with_all_flags_explicitly_off(monkeypatch):
    monkeypatch.setenv("PIPELINE_MODE", "fresh")
    for var in FLAG_ENV_VARS[1:]:
        monkeypatch.setenv(var, "0")
    expected = json.loads(GOLDEN_PATH.read_text())
    _assert_same(expected, run_parity_scenario())


if __name__ == "__main__":
    if "--write" not in sys.argv:
        sys.exit("usage: PYTHONPATH=. python tests/test_flags_off_parity.py --write  (only on unmodified main)")
    GOLDEN_PATH.parent.mkdir(parents=True, exist_ok=True)
    records = run_parity_scenario()
    GOLDEN_PATH.write_text(json.dumps(records, indent=1, sort_keys=True) + "\n")
    print(f"wrote {GOLDEN_PATH} ({len(records)} responses)")
