import { useState } from 'react'
import { scenarioMeta } from '../../utils/format.js'

function buildReportText({ patientLabel, patient, assessment, wearable, daysToNext }) {
  if (!assessment) return null
  const scenario = scenarioMeta(assessment.scenario_type)
  const lines = [
    `PATIENT: ${patientLabel}  |  AGE: ${patient?.age ?? '—'}  |  SEX: ${patient?.sex ?? '—'}`,
    `GENERATED: ${new Date(assessment.created_at).toLocaleString()}`,
    '',
    `RISK CLASSIFICATION: ${assessment.risk_bucket}`,
    `NYHA CLASS: ${assessment.nyha_class}`,
    `DETECTED SCENARIO: ${scenario.name}`,
    `SEVERITY INDEX: ${assessment.severity?.toFixed(2) ?? '—'} / 1.00`,
    '',
    'VITALS (LATEST WEARABLE SYNC)',
    `  Heart Rate ......... ${wearable?.resting_hr_bpm ?? '—'} bpm`,
    `  SpO2 ............... ${wearable?.spo2_pct ?? '—'}%`,
    `  Weight ............. ${wearable?.weight_kg ?? '—'} kg`,
    `  Ejection Fraction .. ${assessment.ejection_fraction_pct ?? '—'}%`,
    `  BNP ................ ${assessment.nt_probnp_pg_ml ?? '—'} pg/mL`,
    '',
    'PROJECTION',
    `  Deterioration direction: ${assessment.deterioration_direction ?? '—'}`,
    `  Projected time to next risk tier: ${daysToNext === null ? 'stable / no near-term progression' : `${daysToNext} days`}`,
    '',
    ...(assessment.risk_caveats ? ['CAVEATS', `  ${assessment.risk_caveats}`, ''] : []),
    '-- Generated by HeartGuard AI digital twin. Decision support only. --',
  ]
  return lines.join('\n')
}

export default function DoctorReportCard({ patientLabel, patient, assessment, wearable }) {
  const [copied, setCopied] = useState(false)
  const reportText = buildReportText({ patientLabel, patient, assessment, wearable, daysToNext: assessment?.days_to_next_stage ?? null })

  function handleCopy() {
    if (!reportText) return
    if (navigator.clipboard) navigator.clipboard.writeText(reportText).catch(() => {})
    setCopied(true)
    setTimeout(() => setCopied(false), 1600)
  }

  function handleDownload() {
    if (!reportText) return
    const blob = new Blob([reportText], { type: 'text/plain' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `${patientLabel.replace(/\s+/g, '_')}_HeartGuard_Report.txt`
    a.click()
    setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return (
    <div className="section">
      <div className="doccard">
        <div className="dochead">
          <div className="doctitle">
            <svg width="15" height="15" viewBox="0 0 24 24" fill="none">
              <path d="M6 3h9l5 5v13a1 1 0 01-1 1H6a1 1 0 01-1-1V4a1 1 0 011-1z" stroke="#5EEAD4" strokeWidth="1.6" />
              <path d="M14 3v5h5" stroke="#5EEAD4" strokeWidth="1.6" />
            </svg>
            Clinical Summary Report
          </div>
          <div style={{ display: 'flex', gap: 8 }}>
            <button type="button" className="btn btn-dark" onClick={handleCopy} disabled={!reportText}>
              {copied ? 'Copied ✓' : 'Copy'}
            </button>
            <button type="button" className="btn btn-teal" onClick={handleDownload} disabled={!reportText}>
              Download
            </button>
          </div>
        </div>
        <div className="docbody">{reportText ?? 'No completed assessment yet for this patient.'}</div>
      </div>
      <div className="footnote">
        HeartGuard AI is a decision-support simulation, not a diagnostic device. All projections are
        model estimates — clinical judgment supersedes model output.
      </div>
    </div>
  )
}
